@base_url = https://localhost:5001/drgapi

GET {{base_url}}/PlayedGames?userid=1e6c520c-34a7-41c3-bcad-80b5158128a9


###

GET {{base_url}}/Characters
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImRyZ3dlaXNzIiwibmJmIjoxNjUzODQyMTE5LCJleHAiOjE2NTM4NDU3MTksImlhdCI6MTY1Mzg0MjExOX0.A3n0j-L6EVooah0Q4G-OHG1TJu4Bg2Gro9IK9QyFXss
###
POST {{base_url}}/user/login
Content-Type: application/json

{
    "username": "drgweiss",
    "password": "2B0108KmF"
}
