// <auto-generated />
using DRG_Api.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DRG_Api.Migrations
{
    [DbContext(typeof(PlayedGamesContext))]
    partial class PlayedGamesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("DRG_Api.Models.Platform", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("platform");
                });

            modelBuilder.Entity("DRG_Api.Models.PlayedGame", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("developer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("genre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("platformid")
                        .HasColumnType("int");

                    b.Property<string>("publisher")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<int>("statusid")
                        .HasColumnType("int");

                    b.Property<string>("year")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.HasIndex("platformid");

                    b.HasIndex("statusid");

                    b.ToTable("playedgame");
                });

            modelBuilder.Entity("DRG_Api.Models.Status", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("status");
                });

            modelBuilder.Entity("DRG_Api.Models.PlayedGame", b =>
                {
                    b.HasOne("DRG_Api.Models.Platform", "platform")
                        .WithMany("PlayedGames")
                        .HasForeignKey("platformid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DRG_Api.Models.Status", "status")
                        .WithMany("PlayedGames")
                        .HasForeignKey("statusid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("platform");

                    b.Navigation("status");
                });

            modelBuilder.Entity("DRG_Api.Models.Platform", b =>
                {
                    b.Navigation("PlayedGames");
                });

            modelBuilder.Entity("DRG_Api.Models.Status", b =>
                {
                    b.Navigation("PlayedGames");
                });
#pragma warning restore 612, 618
        }
    }
}
